// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Article struct {
	ID             int    `json:"id"`
	DisplayAppName string `json:"display_app_name"`
	IconSrc        string `json:"icon_src"`
	CvCondition    string `json:"cv_condition"`
	BasePoint      int    `json:"base_point"`
}

type CreateInput struct {
	DisplayAppName string `json:"display_app_name"`
	IconSrc        string `json:"icon_src"`
	CvCondition    string `json:"cv_condition"`
	BasePoint      int    `json:"base_point"`
}

type UpdateInput struct {
	ID             int    `json:"id"`
	DisplayAppName string `json:"display_app_name"`
	IconSrc        string `json:"icon_src"`
	CvCondition    string `json:"cv_condition"`
	BasePoint      int    `json:"base_point"`
}
